name: UI tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: microsoft/playwright-github-action@v1
      - name: Install Dependencies
        run: npm ci && npm install playwright
      - name: Create org
        run: echo "${{secrets.DEVHUB_CI_CERT_2020_PRIVATEKEY}}" | ./create-org.sh "${{secrets.DEVHUB_CI_CERT_2020_CONSUMERKEY}}"
      - name: Run playwright tests
        run: |
          sfdx force:user:create -f config/qa-user-template.json -a qauser
          sfdx force:org:list
          sfdx force:org:open -u qauser -r --loglevel=TRACE --json

