name: UI tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
      - name: Create org and user
        run: |
          sfdx auth:jwt:grant --clientid 3MVG9kBt168mda_9mVxjfYU9ULJLbCx8uXkqQ3cdGV_TdSMUBu9yy2xkFPd20IoFTAYCqaABssagWQ7pgYQiE --jwtkeyfile ./server.key --username j.silute+jan2021@gmail.com -a HubOrg
          sfdx force:org:create -v HubOrg -s -f ./config/ci_scratch_template.json -d 1 -w 10 -a ciorg
          sfdx force:user:create -f config/qa-user-template.json -a qauser
          sfdx force:org:list
          sfdx force:org:open -u qauser -r --loglevel=TRACE --json
