name: UI tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: '12'
#      - uses: microsoft/playwright-github-action@v1
#      - name: Install Dependencies
#        run: npm ci && npm install playwright
      - name: Create org and user
        run: |
          sfdx auth:jwt:grant --clientid 3MVG9SemV5D80oBeX0cnx.ekz5AjR9yfzePjZJlEK4nW1FfV7Z1EJm3cM_opgmAWOjXMF.jfIOuX.7KWGv6cf  --jwtkeyfile ./server.key --username dub.id-pmow@force.com -a HubOrg
          sfdx force:org:create -v HubOrg -s -f ./config/ci_scratch_template.json -d 1 -w 10 -a ciorg
          sfdx force:user:create -f config/qa-user-template.json -a qauser
          sfdx force:org:list
          sfdx force:org:open -u qauser -r --loglevel=TRACE --json

